import Footer from '@/components/home/Footer'
import Navbar from '@/components/Navbar'
import './globals.css'
import Providers from './Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Providers>
        {/* Navbar */}
        <Navbar></Navbar>

        {children}

        {/* Footer */}
      <Footer></Footer>
      </Providers>
        </body>
    </html>
  )
}
